'use strict';
var React = require('react-native');
var{
    StyleSheet,
} = React;
module.exports = StyleSheet.create({
infoButton: {
        marginTop: 30,
        marginBottom: 10,
        borderWidth: 2,
        borderRadius: 10,
        marginLeft: 2,
        marginRight: 2,
        paddingTop: 20,
        paddingBottom: 30,
        paddingLeft: 20,
        paddingRight: 20,
        borderColor:'#ffffff',
        backgroundColor:'#faf658',
        justifyContent: 'center',
        alignItems: 'center'
},
    infotext: {
        marginTop: 20,
        color: 'black',
        fontSize: 25,
        textAlign: 'center',
    },
heading1: {
    fontSize: 25,
        marginTop: 10,
        marginBottom: 10,
        borderWidth: 2,
        borderRadius: 10,
        marginLeft: 2,
        marginRight: 2,
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 20,
        paddingRight: 20,
        overflow: 'hidden',
        textAlign: 'center',
        borderColor:'#ffffff',
        backgroundColor:'#e6e255',
},
heading2: {
    fontSize: 25,
        marginTop: 10,
        marginBottom: 10,
        borderWidth: 2,
        borderRadius: 10,
        marginLeft: 2,
        marginRight: 2,
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 20,
        paddingRight: 20,
        overflow: 'hidden',
        textAlign: 'center',
        borderColor:'#ffffff',
        backgroundColor:'#bab643',
},
heading3: {
    fontSize: 25,
    marginTop: 10,
    marginBottom: 10,
    borderWidth: 2,
    borderRadius: 10,
    marginLeft: 2,
    marginRight: 2,
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    overflow: 'hidden',
    textAlign: 'center',
    borderColor: '#ffffff',
    backgroundColor: '#aeaa42',
    }
});
